language: python
python:
    - "2.7"
node_js:
    - "0.10"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install -r dev-requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
    - "python setup.py develop"
    - "./manage.py syncdb --noinput"
    - "npm install less yuglify karma"
script:
    - "py.test --cov . ."
    - "./karma_tests.sh"
after_success:
    - coveralls
notifications:
    irc:
        channels: "irc.freenode.org#hacklab/"
        use_notice: true
        on_success: change
        on_failure: always
    email:
        recipients:
            - "timtec-dev@listas.hacklab.com.br"
        on_success: change
        on_failure: always
